# Pandas Essentials

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [4]:
# creating a series
data=[x for x in range(1, 6)]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
# creating a dataframe
data={'Name':['Alice', 'Bob', 'David', 'Morrison'],
      'Age':[25, 30, 35, 40],
      'City':['New York', 'Los Angeles', 'Chicago', 'Houston']}
df=pd.DataFrame(data)
df

       Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2     David   35      Chicago
3  Morrison   40      Houston

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [12]:
df.describe()

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [13]:
# indexing & slicing
# select a single column by position
print(df.iloc[:,0])

0       Alice
1         Bob
2       David
3    Morrison
Name: Name, dtype: str

In [16]:
# select rows & column by position
print(df.loc[1:3, ['Name', 'City']])

       Name         City
1       Bob  Los Angeles
2     David      Chicago
3  Morrison      Houston

In [20]:
# select rows & columns by position
df.iloc[0:3, 0:2]

    Name  Age
0  Alice   25
1    Bob   30
2  David   35

In [22]:
# select a single column by label
df['Name']

0       Alice
1         Bob
2       David
3    Morrison
Name: Name, dtype: str

In [45]:
# include null data
nullData={'Name':['Alice', None, 'David', 'Morrison'],
      'Age':[25, 30, None, 40],
      'City':['New York', 'Los Angeles', 'Chicago', 'Houston']}
nullDf=pd.DataFrame(nullData)
nullDf

       Name   Age         City
0     Alice  25.0     New York
1       NaN  30.0  Los Angeles
2     David   NaN      Chicago
3  Morrison  40.0      Houston

In [41]:
# Missing Data Handling
# Drop rows with missing values
nullDf.dropna()

       Name   Age      City
0     Alice  25.0  New York
3  Morrison  40.0   Houston

In [44]:
# fill missing value with a specified value
nullDf.fillna(0)

       Name   Age         City
0     Alice  25.0     New York
1         0  30.0  Los Angeles
2     David   0.0      Chicago
3  Morrison  40.0      Houston